# Generated by Django 5.1.1 on 2025-02-07 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_summary',
            fields=[
                ('all_card_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='全体カードID')),
                ('pack_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='パックコード')),
                ('pack_card_id', models.IntegerField(blank=True, null=True, verbose_name='パック内カードID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='カード名')),
                ('name_english', models.CharField(blank=True, max_length=50, null=True, verbose_name='英語名')),
                ('card_category', models.IntegerField(blank=True, null=True, verbose_name='カードカテゴリ')),
                ('card_class', models.IntegerField(blank=True, null=True, verbose_name='カードクラス')),
                ('rarity', models.IntegerField(blank=True, null=True, verbose_name='レア度')),
            ],
            options={
                'verbose_name_plural': 'card_summary',
                'db_table': 'app1_card_summary',
                'ordering': ['all_card_id'],
                'constraints': [models.UniqueConstraint(fields=('pack_code', 'pack_card_id'), name='pack_unique_id')],
            },
        ),
        migrations.CreateModel(
            name='Card_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.IntegerField(blank=True, null=True, verbose_name='タイプ')),
                ('hp', models.IntegerField(blank=True, null=True, verbose_name='HP')),
                ('ability_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='特性名前')),
                ('ability_txt', models.CharField(blank=True, max_length=255, null=True, verbose_name='特性効果文')),
                ('effect1_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='技1名前')),
                ('effect1_dmg', models.IntegerField(blank=True, null=True, verbose_name='技1ダメージ')),
                ('effect1_txt', models.CharField(blank=True, max_length=255, null=True, verbose_name='技1効果文')),
                ('effect2_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='技2名前')),
                ('effect2_dmg', models.IntegerField(blank=True, null=True, verbose_name='技2ダメージ')),
                ('effect2_txt', models.CharField(blank=True, max_length=255, null=True, verbose_name='技2効果文')),
                ('weakness', models.IntegerField(blank=True, null=True, verbose_name='弱点')),
                ('escape_cost', models.IntegerField(blank=True, null=True, verbose_name='逃げる')),
                ('ex', models.BooleanField(blank=True, null=True, verbose_name='ex')),
                ('all_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_folder.card_summary')),
            ],
            options={
                'verbose_name_plural': 'card_detail',
                'db_table': 'app1_card_detail',
            },
        ),
    ]
