# Generated by Django 5.1.1 on 2025-02-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0002_alter_card_detail_all_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_detail',
            name='all_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='app_folder.card_summary'),
        ),
    ]
