# Generated by Django 5.1.1 on 2025-02-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0003_alter_card_detail_all_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_detail',
            name='all_card',
        ),
        migrations.AddField(
            model_name='card_detail',
            name='card_summary',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_folder.card_summary'),
            preserve_default=False,
        ),
    ]
