# Generated by Django 5.1.1 on 2025-02-15 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0004_remove_card_detail_all_card_card_detail_card_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_detail',
            name='card_summary',
        ),
        migrations.AddField(
            model_name='card_detail',
            name='all_card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='app_folder.card_summary'),
        ),
    ]
